### ISSUE TITLE
[QUESTION]: Blob unique name

### ISSUE THREAD

**Issue by simplecommerce** [brecht-vermeersch/uppy-azure-blob#1]
Hi,

I had a quick question.
When a file is selected and uploaded to the blob storage, it keeps the name of the file that was selected.
So this means that if a user selects multiple times the same file, it will only overwrite the file that has the same name.

I know that on Azure there is a way to have the names be uniquely generated using `{rand-guid}`.

I was wondering is there a built-in way to do this or do I have to change the name myself before uploading?

Thanks!

**Comment by brecht-vermeersch** [comment]
This package is a small adapter for the @azure/storage-blob package. Maybe see what that package suggests?
